apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jooeel98/frontend-quiz-app:latest
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://quizapp.cloudcorehub.com/api/questions"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP